# This file stores configurations for your Shopify app.

scopes = "write_products, read_customers, write_customers, read_orders, write_orders, read_fulfillments, write_fulfillments, read_price_rules, write_price_rules"
